### ISSUE TITLE
Get rid of garbage navbar-side code

### ISSUE THREAD

**Issue by AdamRivelli** [jagath-jaikumar/326-Project#2]
I downloaded some sample code for a bootstrap-styled side-navbar, and it breaks a lot of the homepage. Replace with artisanal, hand-crafted code that works a bit better.

https://github.com/jagath-jaikumar/326-Project/blob/dd5654dff79ddbb37119247b1bfe8b3eb54ceabf/project1/homepage/home.html#L27

**Comment by jagath-jaikumar** [comment]
What was the problem exactly?

**Comment by AdamRivelli** [comment]
Fixed and replaced with grass-fed, steroid free code.
f48523e0e12d0d1054817ffa6dac418a38c6c0f4
