### ISSUE TITLE
Outline Full Data Model

### ISSUE THREAD

**Issue by jeremy6462** [jagath-jaikumar/326-Project#3]
https://sqldbm.com/Project/SQLServer/Share/2SZVCZPVmPVf7dcjpmoYeQ

student

teacher

post

class

message

**Comment by jeremy6462** [comment]
My proposed solution:

student
- id: int
- full_name: string
- year: string
- profile_pic_path: string // a file path?

teacher
- id: int
- full_name: string
- department: string
- profile_pic_path: string // a file path?

class
- id: int
- full_name: string
- department: string
- number: int // ie. 326 for cs 326
- teacher: int FK to teacher
- students: [int] Many to Many 
- posts: [int] one to many

section
- id: int
- year: int
- season: SEASON('fall', 'spring', 'summer', 'winter') 

post
- id: int
- sender: int FK to student
- class: int FK to class
- content: string
- date: datetime

message
- id: int
- sender: int FK to student
- receiver: int FK to student
- content: string
- date: datetime

**Comment by jagath-jaikumar** [comment]
Complete the data model diagram. We recommend using presentation software such as Keynote, Powerpoint, or Google Slides to complete the diagram as you will need this as part of your final presentation at the end of the semester. You must submit a PDF version of your diagram with this project submission.

**Comment by jeremy6462** [comment]
initial draft here: 28c9147a2bd8d9c3c02350ca8d587fba5794c1c7
