### ISSUE TITLE
Decide on Team Choice Element

### ISSUE THREAD

**Issue by jagath-jaikumar** [jagath-jaikumar/326-Project#35]

**Comment by AdamRivelli** [comment]
I didn't read too closely at the team choice element, but could this be implementing the messaging library?

**Comment by jagath-jaikumar** [comment]
Your team choice should be relatively self contained and not overly ambitious. For example, your team may try to incorporate password reset into your application by using email or texting services, or try to use Angular or React, or perhaps your team wants to focus more on how to more efficiently upload files from the browser to the server. This part is wide open and will only be disqualified if you are trying to do something we already covered in class.


messaging seems like a good idea
